version: '3.8'

services:
  mongo:
    image: mongo
    command: mongod --port 27018
    restart: always
    ports:
      - '27018:27018'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - "mongo1_data:/data/db"
      - "mongo1_config:/data/configdb"
    # networks:
    #   - mynetwork

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27018/
      ME_CONFIG_BASICAUTH: false
    # networks:
    #   - mynetwork

volumes:
  mongo1_data:
  mongo1_config:

# networks:
#   mynetwork:
#     driver: bridge
